service: ${file(package.json):name}
version: ${file(package.json):version}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
#  region: us-east-1

package:
  exclude:
    - .gitignore
    - games-api/**
    - characters/**

functions:

  heartbeat: # create any endpoint to create the API in API Gateway
    handler: handlers/heartbeat.handler
    events:
      - http:
          path: /
          method: get

resources:

  Resources:
    restApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}:${self:provider.stage}:ApiGatewayRestApi

  Outputs:
    ApiGatewayRestApi:
      Value:
        "Fn::GetAtt": [ restApi, RootResourceId ]
      Export:
        Name: ${self:service}:${self:provider.stage}:RootResourceId
